### ISSUE TITLE
Help me plss  ! publish message on android studio 

### ISSUE THREAD

**Issue by 6010110254** [blundell/CloudIoTCoreMQTTExample#2]
I have created a button for a publis message with a function when clicked. Send a message to the device, but when I click it, the program doesn't work, it bounced off the program as if it couldn't connect

![Screenshot (289)](https://user-images.githubusercontent.com/47842161/102711232-94bb1080-42ea-11eb-90cf-b8a08893fe1d.png)

![Screenshot (290)](https://user-images.githubusercontent.com/47842161/102711275-e8c5f500-42ea-11eb-960a-96966c4fb8d9.png)
![Screenshot (291)](https://user-images.githubusercontent.com/47842161/102711276-e9f72200-42ea-11eb-88c2-dc4137e1a7a3.png)

**Comment by 6010110254** [comment]
file in rsa_private.pem 
![Screenshot (292)_LI](https://user-images.githubusercontent.com/47842161/102711320-422e2400-42eb-11eb-9a2a-c26a182709e9.jpg)

**Comment by 6010110254** [comment]
UI design for publish message Onclick
![Screenshot (293)](https://user-images.githubusercontent.com/47842161/102711333-6c7fe180-42eb-11eb-91cf-ca978c002fda.png)

**Comment by blundell** [comment]
I haven't looked at this project in a while, but it uses the LocalBroadcastManager here: 

https://github.com/blundell/CloudIoTCoreMQTTExample/blob/master/app/src/main/java/android/support/v4/content/LocalBroadcastManager.java

However your error is androix BroadcastManager, so you have either added a new dependency and its changed or you are missing a dependency. 

Hope that helps
